workflows:
  version: 2
  main:
    jobs:
      - lint
      - test-php

version: 2

jobs:
  lint:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - run: |
          php --version
      - checkout
      - restore_cache:
          keys:
            - &composer-cache composer-deps-{{ checksum "composer.lock" }}
            - composer-deps-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: *composer-cache
          paths:
            - vendor
      - run:
          name: "Run PHP Lint"
          command: |
            composer phpcs
