workflows:
  version: 2
  main:
    jobs:
      - lint
      - test-php

version: 2

jobs:
  lint:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - run: |
          php --version
      - checkout
      - restore_cache:
          keys:
            - &composer-cache composer-deps-{{ checksum "composer.lock" }}
            - composer-deps-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: *composer-cache
          paths:
            - vendor
      - run:
          name: "Run PHP Lint"
          command: |
            composer phpcs
  test-php:
    docker:
      - image: cimg/php:8.2-node
      - image: cimg/mysql:8.0
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - run: |
          php --version
          node --version
      - checkout
      - restore_cache:
          keys:
            - &composer-cache composer-deps-{{ checksum "composer.lock" }}
            - composer-deps-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: *composer-cache
          paths:
            - vendor
      - run:
          name: "Install Extras"
          command: |
            sudo apt-get update
            sudo apt-get install subversion
            sudo apt-get install mysql-client
      - run:
          name: "Run Tests"
          command: |
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            composer phpunit
            WP_MULTISITE=1 composer phpunit
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 nightly true
            composer phpunit
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 4.4 true
            composer phpunit
